version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./static:/app/static
      - media_volume:/app/media
    expose:
      - 8000
    environment:
      - DJANGO_SETTINGS_MODULE=test_manager.settings
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - media_volume:/app/media
    ports:
      - "8080:80"
    depends_on:
      - web
    restart: unless-stopped

volumes:
  media_volume:
