# Generated by Django 5.2 on 2025-04-13 09:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "permissions": [
                    ("manage_project", "Can manage project settings and members"),
                    ("edit_tests", "Can create and edit test cases"),
                    ("execute_tests", "Can execute tests and record results"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("prerequisites", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "下書き"),
                            ("ACTIVE", "有効"),
                            ("DEPRECATED", "非推奨"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("HIGH", "高"), ("MEDIUM", "中"), ("LOW", "低")],
                        default="MEDIUM",
                        max_length=6,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TestSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("executed_by", models.CharField(blank=True, max_length=100)),
                ("environment", models.CharField(blank=True, max_length=200)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_sessions",
                        to="test_manager.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("executed_by", models.CharField(blank=True, max_length=100)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_TESTED", "未テスト"),
                            ("PASS", "合格"),
                            ("FAIL", "不合格"),
                            ("BLOCKED", "ブロック"),
                            ("SKIPPED", "スキップ"),
                        ],
                        default="NOT_TESTED",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("result_detail", models.TextField(blank=True, verbose_name="詳細")),
                ("environment", models.CharField(blank=True, max_length=200)),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="test_manager.testcase",
                    ),
                ),
                (
                    "test_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="test_manager.testsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestSuite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_suites",
                        to="test_manager.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "name")},
            },
        ),
        migrations.AddField(
            model_name="testsession",
            name="available_suites",
            field=models.ManyToManyField(
                help_text="このテストセッションで選択可能なテストスイート",
                related_name="available_test_sessions",
                to="test_manager.testsuite",
            ),
        ),
        migrations.AddField(
            model_name="testcase",
            name="suite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_cases",
                to="test_manager.testsuite",
            ),
        ),
        migrations.CreateModel(
            name="TestStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("description", models.TextField(help_text="実行する操作の内容")),
                (
                    "expected_result",
                    models.TextField(blank=True, help_text="この操作で期待される結果"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="test_manager.testcase",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("test_case", "order")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="testcase",
            unique_together={("suite", "title")},
        ),
    ]
