# Generated by Django 5.2.1 on 2025-05-22 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testsession",
            name="available_suites",
        ),
    ]
