# Generated by Django 5.1.6 on 2025-03-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_tracking", "0004_change_testrun_relation_to_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testrun",
            name="environment",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="testrun",
            name="executed_by",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
