# Generated by Django 5.1.6 on 2025-03-01 14:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def copy_test_runs_to_iterations(apps, schema_editor):
    TestRun = apps.get_model('test_tracking', 'TestRun')
    TestIteration = apps.get_model('test_tracking', 'TestIteration')
    
    for test_run in TestRun.objects.all():
        test_iteration = TestIteration.objects.create(
            name=test_run.name,
            description=test_run.description,
            executed_by=test_run.executed_by,
            environment=test_run.environment,
            started_at=test_run.started_at,
            completed_at=test_run.completed_at,
            project=test_run.project
        )
        test_iteration.available_suites.set(test_run.available_suites.all())
        test_iteration.save()
        
        # TestExecutionのtest_run_idをtest_iteration_idにコピー
        test_run.executions.all().update(test_iteration=test_iteration)


class Migration(migrations.Migration):

    dependencies = [
        (
            "test_tracking",
            "0006_alter_project_name_alter_testcase_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TestIteration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("executed_by", models.CharField(blank=True, max_length=100)),
                ("environment", models.CharField(blank=True, max_length=200)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "available_suites",
                    models.ManyToManyField(
                        help_text="このテストイテレーションで選択可能なテストスイート",
                        related_name="available_test_iterations",
                        to="test_tracking.testsuite",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_iterations",
                        to="test_tracking.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="testexecution",
            name="test_iteration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="test_tracking.testiteration",
            ),
        ),
        migrations.RunPython(copy_test_runs_to_iterations),
        migrations.RemoveField(
            model_name="testexecution",
            name="test_run",
        ),
        migrations.DeleteModel(
            name="TestRun",
        ),
        migrations.AlterField(
            model_name="testexecution",
            name="test_iteration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="test_tracking.testiteration",
            ),
        ),
    ]
