# Generated by Django 5.1.6 on 2025-03-02 05:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def migrate_test_iterations_to_sessions(apps, schema_editor):
    TestIteration = apps.get_model('test_tracking', 'TestIteration')
    TestSession = apps.get_model('test_tracking', 'TestSession')
    TestExecution = apps.get_model('test_tracking', 'TestExecution')

    # TestIterationからTestSessionへデータを移行
    for iteration in TestIteration.objects.all():
        session = TestSession.objects.create(
            name=iteration.name,
            description=iteration.description,
            executed_by=iteration.executed_by,
            environment=iteration.environment,
            started_at=iteration.started_at,
            completed_at=iteration.completed_at,
            project=iteration.project,
        )
        # ManyToManyフィールドの移行
        session.available_suites.set(iteration.available_suites.all())
        # 関連するTestExecutionの移行
        TestExecution.objects.filter(test_iteration=iteration).update(test_session=session)


class Migration(migrations.Migration):

    dependencies = [
        ("test_tracking", "0007_remove_testexecution_test_run_testiteration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("executed_by", models.CharField(blank=True, max_length=100)),
                ("environment", models.CharField(blank=True, max_length=200)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "available_suites",
                    models.ManyToManyField(
                        help_text="このテストセッションで選択可能なテストスイート",
                        related_name="available_test_sessions",
                        to="test_tracking.testsuite",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_sessions",
                        to="test_tracking.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="testexecution",
            name="test_session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="test_tracking.testsession",
            ),
        ),
        migrations.RunPython(migrate_test_iterations_to_sessions),
        migrations.RemoveField(
            model_name="testexecution",
            name="test_iteration",
        ),
        migrations.DeleteModel(
            name="TestIteration",
        ),
        migrations.AlterField(
            model_name="testexecution",
            name="test_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="test_tracking.testsession",
            ),
        ),
    ]
